export default {

    // PRICING TOOL - CALCULATOR
    COLLAPSE_PRICING_TOOL: "COLLAPSE_PRICING_TOOL",
    TOGGLE_CALCULATOR: "TOGGLE_CALCULATOR",
    TOGGLE_RESULT: "TOGGLE_RESULT",
    SET_RESULT: "SET_RESULT",
    CHANGE_HANDLER : "CHANGE_HANDLER",
    CALCULATE_RATES: "CALCULATE_RATES",
    SET_ANIMATION: "SET_ANIMATION",
    RESET_TOOL: "RESET_TOOL",

    // AUTHENTICATION
    AUTH_CHANGE_HANDLER: "AUTH_CHANGE_HANDLER",
    VALIDATE_USER: "VALIDATE_USER",
    LOG_OUT: "LOG_OUT"
};